server:
  port: 3000

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/multi_factor?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootpassword

jwt:
  secret: "-----BEGIN PUBLIC KEY-----MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAurSWS32q4eAAVVp3NEHx0n0Pp6V9/g/l3idyeQCE2xImmjrSuOthJYgzjvulPhpJRH3uz0EsKHUUxBoC2M9uM2S7jmiJzfEHctxPBwyLiueisFYRBuMoBLPF/08h7WEbVKk2Ku/tJ4cYle9ukrUEvu1zfu4lcRkS3PVp4g6CeklaQet7CYm5b7JhZg2/W08aV7qBUK8vs0jAtJfQUNNCLl6m7CJyfeHs9L3E8pcVYYqTlG0SewNJ8sn7nOhTPIIoU85y67NmnO/zq9V9ZplYZm1x/8Zd52A3Vf6iU14tzE8ZIwD/Tcf6nopCwmCn9UGrS9nKRj9fwlRwK6iXyI0ASrFfxVtzS1eIxzq7hIkWsepCb3P+awcRQrn/qChIEsDzv2gKwWEthFR9KFi46T/tapUbRQ+zyJ1tYB3PQQt6v7/N1qIl2Vztyy8+rVtnD3TJwrSBM/1K08SRNyKlLrbxT1RO5ZgrCug98a6FksG2CkBTJ2RsElySX1lMRmbKibyLbRQRo8O77lhzO0tgN90gKvlR5+jgoUiSHTsSTHqAFApFQI4gMOUf4WvAZXdplIqIQWKTcSwiYAUa7dCCP3XaynLO56rBId1HBw/mi8dNMYhiXq/X9f/qPBw14oqWhV1Ub/kOhyl9TGbhnMtvDYQy3kJxm5a5mXprrf63YtTuPoMCAwEAAQ==-----END PUBLIC KEY-----"

otp-policy:
  code-length: 6
  code-expiry: 30
  code-invalid-attempt: 3

pin-policy:
  code-length: 4
  code-invalid-attempt: 3

multi-factor-policy:
  method:
    primary: 'VERIDIUM'
    secondary: 'SMS_CODE'
  soft-token:
    token-length: 32
  attempts:
    max: 3
  rules:
    - name: 'first time login'
      description: 'rule to trigger multi factor at first time login'
      code: 'FIRST_TIME_LOGIN'